Update project.yml

diff --git a/.github/workflows/project.yml b/.github/workflows/project.yml
--- a/.github/workflows/project.yml
+++ b/.github/workflows/project.yml
@@ -1206,20 +1206,47 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        script:
-          - {name: 'ocr', path: 'OCR', command: 'python ocr_marcadona.py'},
-          - {name: 'customers', path: 'customers', command: 'sm_retail_customer.py'},
-          # - {name: 'catalonia_establishment_location', path: 'catalonia_establishment_location', command: 'establishments_scraper.py'},
-          # - {name: 'flipkart', path: 'Flipkart', command: 'scrap_flipkart_pages_sel.py'},
-          # - {name: 'Eatbydate', path: 'eat_by_date', command: 'eat_by_date.py'},
-          - { name: 'Mealdb', path: 'meal_db/mealscraper', script: 'scrapy crawl mealdb -O ./data/raw/mealdb.json' }
-          - { name: 'ApprovedFood', path: 'approved_food_uk/approvedfood_scraper', script: 'scrapy crawl approvedfood_groceries -O ./data/raw/Approvedfood.json' }
-          - { name: 'BigBasket', path: 'big_basket', script: 'python big_basket.py' }
-          - { name: 'CustomerLocation', path: 'synthetic/customer_location', script: 'python customer_location.py' }
-          - { name: 'CustomerPurchase', path: 'synthetic/customer_purchase', script: 'python customer_purchase.py' }
-          - { name: 'Business_SentimentReview', path: 'synthetic/sentiment reviews', script: 'python business_reviews.py' }
-          - { name: 'Individual_SentimentReview', path: 'synthetic/sentiment reviews', script: 'python individual_reviews.py' }
-          - { name: 'SupermarketProducts', path: 'synthetic/supermarket_products', script: 'python supermarket_products.py' }
+        include:
+          - name: 'ocr'
+            path: 'OCR'
+            command: 'python ocr_marcadona.py'
+          - name: 'customers'
+            path: 'customers'
+            command: 'python sm_retail_customer.py'
+          # - name: 'catalonia_establishment_location'
+            # path: 'catalonia_establishment_location'
+            # command: 'python establishments_scraper.py'
+          # - name: 'flipkart'
+          #   path: 'Flipkart'
+          #   command: 'python scrap_flipkart_pages_sel.py'
+          # - name: 'Eatbydate'
+          #   path: 'eat_by_date'
+          #   command: 'python eat_by_date.py'
+          - name: 'Mealdb'
+            path: 'meal_db/mealscraper'
+            command: 'scrapy crawl mealdb -O ./data/raw/mealdb.json'
+          - name: 'ApprovedFood'
+            path: 'approved_food_uk/approvedfood_scraper'
+            command: 'scrapy crawl approvedfood_groceries -O ./data/raw/Approvedfood.json'
+          - name: 'BigBasket'
+            path: 'big_basket'
+            command: 'python big_basket.py'
+          - name: 'CustomerLocation'
+            path: 'synthetic/customer_location'
+            command: 'python customer_location.py'
+          - name: 'CustomerPurchase'
+            path: 'synthetic/customer_purchase'
+            command: 'python customer_purchase.py'
+          - name: 'Business_SentimentReview'
+            path: 'synthetic/sentiment reviews'
+            command: 'python business_reviews.py'
+          - name: 'Individual_SentimentReview'
+            path: 'synthetic/sentiment reviews'
+            command: 'python individual_reviews.py'
+          - name: 'SupermarketProducts'
+            path: 'synthetic/supermarket_products'
+            command: 'python supermarket_products.py'
+
     steps:
       - uses: actions/checkout@v2
 
@@ -1241,22 +1268,22 @@ jobs:
       - name: Execute Script
         run: |
           mkdir -p ./logs
-          ${{ matrix.script.script }} > ./logs/${{ matrix.script.name }}_output.log 2> ./logs/${{ matrix.script.name }}_error.log || echo "Script failed, check logs."
-        working-directory: ./landing_zone/collectors/${{ matrix.script.path }}
+          cd ./landing_zone/collectors/${{ matrix.path }}
+          ${{ matrix.command }} > ../../logs/${{ matrix.name }}_output.log 2> ../../logs/${{ matrix.name }}_error.log || echo "Script failed, check logs."
         continue-on-error: true
 
       - name: Prepare error log
         if: failure()
         run: |
           echo "ERROR_LOG<<EOF" >> $GITHUB_ENV
-          cat ./logs/${{ matrix.script.name }}_error.log >> $GITHUB_ENV
+          cat ./logs/${{ matrix.name }}_error.log >> $GITHUB_ENV
           echo "EOF" >> $GITHUB_ENV
 
       - name: Upload error log to Gist
         if: failure()
         run: |
-          LOG_CONTENT=$(cat ./logs/${{ matrix.script.name }}_error.log)
-          JSON_PAYLOAD="{\"description\": \"Error Log for ${{ matrix.script.name }}\", \"public\": true, \"files\": {\"error_log.txt\": {\"content\": \"$LOG_CONTENT\"}}}"
+          LOG_CONTENT=$(cat ./logs/${{ matrix.name }}_error.log)
+          JSON_PAYLOAD="{\"description\": \"Error Log for ${{ matrix.name }}\", \"public\": true, \"files\": {\"error_log.txt\": {\"content\": \"$LOG_CONTENT\"}}}"
           GIST_URL=$(curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d "$JSON_PAYLOAD" https://api.github.com/gists | jq -r '.html_url')
           echo "GIST_URL=$GIST_URL" >> $GITHUB_ENV
 
@@ -1270,14 +1297,13 @@ jobs:
               "attachments": [
                 {
                   "color": "${{ job.status == 'success' ? '#36a64f' : '#ff0000' }}",
-                  "text": "${{ matrix.script.name }} Script\nStatus: ${{ job.status }}\nError Log: <${{ env.GIST_URL }}|View Log>\nDate: ${{ env.CURRENT_DATE }}\nCommit: ${{ github.sha }}\nAuthor: ${{ github.actor }}\nRepo: ${{ github.repository }}"
+                  "text": "${{ matrix.name }} Script\nStatus: ${{ job.status }}\nError Log: <${{ env.GIST_URL }}|View Log>\nDate: ${{ env.CURRENT_DATE }}\nCommit: ${{ github.sha }}\nAuthor: ${{ github.actor }}\nRepo: ${{ github.repository }}"
                 }
               ]
             }
         env:
           SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/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"
 
- 
   
   
   
