Update project.yml

diff --git a/.github/workflows/project.yml b/.github/workflows/project.yml
--- a/.github/workflows/project.yml
+++ b/.github/workflows/project.yml
@@ -271,44 +271,44 @@ jobs:
             echo "::set-output name=error::None"
           fi
 
-  run_eat_by_date:
-    runs-on: ubuntu-latest
-    outputs:
-      script_name: 'Eat by Date Script'
-      status: ${{ steps.set_status.outputs.status }}
-      error: ${{ steps.set_status.outputs.error }}
-    steps:
-      - uses: actions/checkout@v2
-      - uses: actions/setup-python@v4
-        with:
-          python-version: '3.10'
-      - uses: actions/cache@v3
-        with:
-          path: ~/.cache/pip
-          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install -r requirements.txt
-      - name: Execute eat_by_date.py script
-        run: |
-          python eat_by_date.py 2>eat_by_date_error.log || echo "error" > eat_by_date_error.log
-        working-directory: ./landing_zone/collectors/eat_by_date
-      - name: Set job status and error
-        id: set_status
-        if: always()
-        run: |
-          if [ -s eat_by_date_error.log ]; then
-            ERROR_MSG=$(<eat_by_date_error.log)
-            echo "::set-output name=status::failure"
-            echo "::set-output name=error::$ERROR_MSG"
-          else
-            echo "::set-output name=status::success"
-            echo "::set-output name=error::None"
-          fi
+  # run_eat_by_date:
+  #   runs-on: ubuntu-latest
+  #   outputs:
+  #     script_name: 'Eat by Date Script'
+  #     status: ${{ steps.set_status.outputs.status }}
+  #     error: ${{ steps.set_status.outputs.error }}
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #     - uses: actions/setup-python@v4
+  #       with:
+  #         python-version: '3.10'
+  #     - uses: actions/cache@v3
+  #       with:
+  #         path: ~/.cache/pip
+  #         key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
+  #     - name: Install dependencies
+  #       run: |
+  #         python -m pip install --upgrade pip
+  #         pip install -r requirements.txt
+  #     - name: Execute eat_by_date.py script
+  #       run: |
+  #         python eat_by_date.py 2>eat_by_date_error.log || echo "error" > eat_by_date_error.log
+  #       working-directory: ./landing_zone/collectors/eat_by_date
+  #     - name: Set job status and error
+  #       id: set_status
+  #       if: always()
+  #       run: |
+  #         if [ -s eat_by_date_error.log ]; then
+  #           ERROR_MSG=$(<eat_by_date_error.log)
+  #           echo "::set-output name=status::failure"
+  #           echo "::set-output name=error::$ERROR_MSG"
+  #         else
+  #           echo "::set-output name=status::success"
+  #           echo "::set-output name=error::None"
+  #         fi
 
   notify_slack:
-    needs: [run_Mealdb, run_ApprovedFood, run_eat_by_date]
+    needs: [run_Mealdb, run_ApprovedFood] #, run_eat_by_date]
     runs-on: ubuntu-latest
     steps:
       - name: Set current date
@@ -321,8 +321,8 @@ jobs:
           custom_payload: |
             {
               "attachments": [{
-                "color": "${{ needs.run_Mealdb.outputs.status }} === 'success' && '${{ needs.run_ApprovedFood.outputs.status }} === 'success' && '${{ needs.run_eat_by_date.outputs.status }} === 'success' ? 'good' : 'danger'",
-                "text": "Workflow: ${{ github.workflow }}\nDate: ${{ env.CURRENT_DATE }}\nJob: Detailed Status Update\n- Mealdb Script Status: ${{ needs.run_Mealdb.outputs.status }} (Error: ${{ needs.run_Mealdb.outputs.error }})\n- ApprovedFood Script Status: ${{ needs.run_ApprovedFood.outputs.status }} (Error: ${{ needs.run_ApprovedFood.outputs.error }})\n- Eat by Date Script Status: ${{ needs.run_eat_by_date.outputs.status }} (Error: ${{ needs.run_eat_by_date.outputs.error }})\nCommit: ${{ github.sha }}\nAuthor: ${{ github.actor }}\nRepo: ${{ github.repository }}"
+                "color": "${{ needs.run_Mealdb.outputs.status }} === 'success' && '${{ needs.run_ApprovedFood.outputs.status }} === 'success' ? 'good' : 'danger'", 
+                "text": "Workflow: ${{ github.workflow }}\nDate: ${{ env.CURRENT_DATE }}\nJob: Detailed Status Update\n- Mealdb Script Status: ${{ needs.run_Mealdb.outputs.status }} (Error: ${{ needs.run_Mealdb.outputs.error }})\n- ApprovedFood Script Status: ${{ needs.run_ApprovedFood.outputs.status }} (Error: ${{ needs.run_ApprovedFood.outputs.error }})\nCommit: ${{ github.sha }}\nAuthor: ${{ github.actor }}\nRepo: ${{ github.repository }}"
               }]
             }
         env:
